# this is optional and for info purposes only, not a basis for this file
version: '3.8'

# list of containers
services:
    web: # service name for our web server and php
      container_name: docker-front
      restart: on-failure:5 #always
      image: front_insectid
      external_links:
        - docker-back:api
      networks:
        - front-red
        - backend_back-red
      ports:
        - 8501:8501 # map TCP port 80 to xxxx
      # - "0.0.0.0:4004:443" # other format to specify the port mapping
      volumes:
         - ./streamlit_agent/:/app/streamlit_agent 
      build: # there may be cases where you need to customize an image from Docker Hub, so instead of specifying an image for this service, we will define the image via the Dockerfile
      #  context: . # path to where the Dockerfile resides
        dockerfile: Dockerfile # name of the Dockerfile, default is Dockerfile, you can omit this if you follow the standard naming

networks: # an app usually needs multiple services to function, defining a network groups these services to create the app environment
  front-red: {}
  backend_back-red: # <network-name> - in Docker Desktop, this will be prepended with the folder name
    external: true # driver: bridge # bridge is the default driver, so you can omit this line

volumes: # we are going to persist the db data using volumes so that even if you stop the container, the data will persist within docker
  dbdata: # <volume-name> - in Docker Dsektop, this will be prepended with the folder name